version: '3.4'

services:
  xmlmicroservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44368
    ports:
      - "52095:80"
      - "44368:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  xmlmicroservicecar:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  xmlmicroserviceapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  xmlmicroservicead:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

